### ISSUE TITLE
Support freertos

### ISSUE THREAD

**Issue by Nanmei** [exothink/eXoCAN#22]
Can exocan library support freertos?

**Comment by exothink** [comment]
I have no experience with Freertos. Sorry.
________________________________
From: Nanmei ***@***.***>
Sent: Monday, January 22, 2024 4:31 AM
To: exothink/eXoCAN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [exothink/eXoCAN] Support freertos (Issue #22)

Can exocan library support freertos? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: <exothink/eXoCAN/issues/22@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message is From an External Sender: Use caution opening files, clicking links or responding to requests.

ZjQcmQRYFpfptBannerEnd

Can exocan library support freertos?

**Comment by Nanmei** [comment]
I test exocan in freertos can work, thank you so much for your project.
